### ISSUE TITLE
Biomes change after generation

### ISSUE THREAD

**Issue by TheLoneWolfling** [BrainSlugs83/NewBiospheresMod#24]
Look at [this](https://www.dropbox.com/s/q8g0atoqveqao3u/Weird.zip?dl=0) saved world. Go to x109 / y80 / z-135. Notice that it's a Savanna Plateau biome.

Now go to the new world screen and copy the world. Go to the same coordinates. Notice that it is a Forest biome. Then restart the game, and notice it's a Savanna Plateau biome.

The above is all in 0.85. However, it's a problem with 0.8 as well: It also occurs in worlds generated / played with 0.8:

Look at [this](https://www.dropbox.com/s/m4i2euu5j8qkt7y/Weird2.zip?dl=0) saved world. Go to x -110 / y 59 / z 152. Notice it's a desert biome. Restart the game, and now it's a Mesa (Bryce) biome.

I need to check if it's related to chunk unload, world unload, or what.

**Comment by TheLoneWolfling** [comment]
Alright, it happens the first time the chunk unloads. Which probably implies that biomes are getting regenerated somewhere, and with the wrong seed to boot.

Although, interestingly, it seems to be deterministic, and it only changes on the first chunk unload / reload.

**Comment by BrainSlugs83** [comment]
Okay, so this is weird -- I load that world from scratch (Weird.zip) -- and go to that location (looks like you're already there) -- I see the patchwork (guessing this is from existing biome change) -- but it's not a Savanna Plateau biome.  It's a Forest biome....

Did it toggle back to Forest somehow? (I just unzipped and loaded it -- did not clone, etc.)

**Comment by BrainSlugs83** [comment]
... Just to be sure -- you don't have any other mods loaded, right?

**Comment by BrainSlugs83** [comment]
My bad -- it's BOTH biomes -- like when you're on the patchwork tiles it's  Savanna Plateau, and when you're off the patchwork it's forest -- how can a biome be 1x1 like that??

**Comment by BrainSlugs83** [comment]
I'm able to reproduce this effect on a new copy of the world as well -- (no unload TMK has happened yet).

**Comment by BrainSlugs83** [comment]
Well... I'm certainly seeing the patchwork... (without unload/reload) -- I noticed that if I set my spawn point to a location and then jumped into the void, the location would change to that biome -- also -- I noticed the patch work seemed to increase as more entities spawned -- Could it be related to where entities are spawning?

**Comment by BrainSlugs83** [comment]
Heck -- even in the starting biome (in Weird.zip) you can see this -- it's always at a different spot -- but if you look around for it -- you can find it. -- no need to save or reload. -- I'm not sure if it's related to animal spawn or if that's just in my head -- I just found the one in a newly created clone of the map, and it's right by a bunch of animals.

**Comment by BrainSlugs83** [comment]
You might be on to something with the chunk unload thing (I just noticed chunks unloading undeterministically while playing, even though I hadn't even moved around yet).

**Comment by BrainSlugs83** [comment]
Wow -- that was kind of ridiculous.

So -- here's what happened:  Chunks have a 16x16 cache of biomes -- and if this is empty, they calculate what the biome is supposed to be with the default methods -- it decided the biome was supposed to be a forest.

Every now and then, minecraft would ask the mod what the biome was supposed to be instead of the chunk's cache -- and the mod would tell it Savanna Plateau.

During chunk creation, if we just supply a 256 byte array (that's been Arrays.fill'd to the correct value for the expected biome).  The biome comes through correctly.

So, apparently, this whole time, the biomes have been completely wrong.

Awesome. -- I wonder what else is wrong that I haven't noticed yet. :-/

**Comment by BrainSlugs83** [comment]
@TheLoneWolfling -- I uploaded a new build (not sure if you have the ability to make your own builds or not) here: https://github.com/BrainSlugs83/NewBiospheresMod/raw/master/Testing/NewBiospheresMod-Experimental-2015-04-16.jar

When you have a moment, do you mind testing and seeing if the biome issues you logged are fixed in this new build?

**Comment by TheLoneWolfling** [comment]
Yeah I will go through and take a look, although it'll have to be later as I have an exam today.

Good detective work! A caching issue makes sense.

I do have the ability to do my own builds - been playing around with a few minor tweaks, although as of yet I haven't really had time to do anything commit-worthy.

**Comment by BrainSlugs83** [comment]
Awesome, thanks man! -- good luck on your exam, btw. :D

**Comment by TheLoneWolfling** [comment]
I haven't seen any weirdness with that build yet. I'll keep an eye out, but until/unless I reproduce #24 / #14 / #13 I am going to assume they are fixed.

**Comment by BrainSlugs83** [comment]
Woot!
